services:
  postgres-e2e:
    image: postgres:18
    container_name: postgres-e2e
    restart: always
    environment:
      TZ: Europe/Kyiv
      POSTGRES_USER: playground
      POSTGRES_PASSWORD: playground
      POSTGRES_DB: playground_db
    volumes:
      - ./init-data/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - e2e_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U playground -d playground_db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles: [ci, local]

  postgres-auth-e2e:
    image: postgres:18
    container_name: postgres-auth-e2e
    restart: always
    environment:
      TZ: Europe/Kyiv
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - ./init-data/postgres-auth:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - e2e_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles: [ci, local]

networks:
  e2e_network:
    external: true
