# Spring settings
#
spring.application.name=MegaTestApi
server.port=8080
server.servlet.context-path=/api/v1
spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.static-path-pattern=/static
#spring.web.resources.add-mappings=false
spring.main.allow-bean-definition-overriding=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
#
# Swagger OpenApi settings
#
springdoc.packages-to-scan=com.knubisoft.testapi.api
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.tryItOutEnabled=true
#
# Websocket settings
#
spring.websocket.enabled=true
#
# GraphQL settings
#
graphql.mongodb.enabled=true
spring.data.mongodb.database.graphql=graphql_db
#
# MySQL settings
#
mysql.enabled=true
mysql.datasource.jdbcUrl=jdbc:mysql://mysql-e2e:3306/playground_db
mysql.datasource.username=playground
mysql.datasource.password=playground
mysql.datasource.driverClassName=com.mysql.cj.jdbc.Driver
mysql.datasource.hibernate.hbm2ddl.auto=none
mysql.datasource.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
# PostgreSQL settings
#
postgres.enabled=true
postgres.datasource.jdbcUrl=jdbc:postgresql://postgres-e2e:5432/playground_db
postgres.datasource.username=playground
postgres.datasource.password=playground
postgres.datasource.driverClassName=org.postgresql.Driver
postgres.datasource.hibernate.hbm2ddl.auto=none
postgres.datasource.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
# PostgreSQL for Auth settings
#
jwt.postgres.users.enabled=true
basic.postgres.users.enabled=true
postgres.users.datasource.jdbcUrl=jdbc:postgresql://postgres-auth-e2e:5432/users_db
postgres.users.datasource.username=user
postgres.users.datasource.password=password
postgres.users.datasource.driverClassName=org.postgresql.Driver
postgres.users.datasource.hibernate.hbm2ddl.auto=none
postgres.users.datasource.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
# Oracle DB settings
#
oracle.enabled=true
oracle.datasource.jdbcUrl=jdbc:oracle:thin:@oracle-e2e:1521/xe
oracle.datasource.username=c##testlum
oracle.datasource.password=password
oracle.datasource.driverClassName=oracle.jdbc.OracleDriver
oracle.datasource.hibernate.hbm2ddl.auto=none
oracle.datasource.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
#
# ClickHouse DB settings
#
clickhouse.enabled=true
clickhouse.datasource.jdbcUrl=jdbc:clickhouse://clickhouse-e2e:8123/test_db
clickhouse.datasource.username=testlum
clickhouse.datasource.password=testlum-clickhouse
clickhouse.datasource.database=test_db
clickhouse.datasource.driverClassName=ru.yandex.clickhouse.ClickHouseDriver
clickhouse.datasource.hibernate.dialect=org.hibernate.dialect.SQLServer2008Dialect
#
# DynamoDB settings
#
dynamodb.enabled=true
amazon.dynamodb.endpoint=http://dynamodb-e2e:8000
amazon.aws.region=eu-central-1
amazon.aws.accesskey=dHwXPbnU9FVb3o
amazon.aws.secretkey=Kbg7XdQ2YD5hAh
#
# MongoDB settings
#
mongodb.enabled=true
#spring.data.mongodb.uri=mongodb://mongodb-e2e:27017
spring.data.mongodb.host=mongodb-e2e
spring.data.mongodb.port=27017
spring.data.mongodb.database=mongo_db
spring.data.mongodb.username=username
spring.data.mongodb.password=password
#spring.data.mongodb.authentication-database=admin
#
# Redis settings
#
redis.enabled=true
spring.redis.host=redis-e2e
spring.redis.port=6379
#
# RabbitMQ settings
#
rabbitmq.enabled=true
spring.rabbitmq.template.exchange=directExchange
spring.rabbitmq.host=rabbitmq-e2e
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.queue.in=in
rabbitmq.queue.out=out
rabbitmq.routing-key.in=inRoutingKey
rabbitmq.routing-key.out=outRoutingKey
#
# Kafka settings
#
kafka.enabled=true
spring.kafka.bootstrap-servers=kafka-e2e:9093
spring.kafka.consumer.group-id=123
spring.kafka.consumer.client-id=456
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.template.default-topic=topicOne
#
# SQS settings
#
amazon.sqs.enabled=true
amazon.sqs.queue.name=sqs
amazon.sqs.access-key=JQttVjEfR3y4UJ
amazon.sqs.secret-key=wzsTjXDJL2C5Wq
amazon.sqs.service-endpoint=http://localstack-e2e:4566
amazon.sqs.region=eu-central-1
#
# AWS Lambda settings
#
lambda.mongo.enabled=true
amazon.lambda.endpoint=http://localstack-e2e:4566
amazon.lambda.region=eu-central-1
amazon.lambda.accesskey=JQttVjEfR3y4UJ
amazon.lambda.secretkey=wzsTjXDJL2C5Wq
#
# S3 settings
#
s3.enabled=true
aws.s3.endpoint=http://localstack-e2e:4566
aws.s3.access.key=JQttVjEfR3y4UJ
aws.s3.secret.key=wzsTjXDJL2C5Wq
aws.s3.region=eu-central-1
#
# Elasticsearch settings
#
es.enabled=true
spring.data.es.url=elasticsearch-e2e:9200
spring.data.es.username=elastic
spring.data.es.password=q98374fkjdkfuyqiweysdc
#