ALTER SESSION SET CONTAINER = TESTLUM;

CREATE USER testlum IDENTIFIED BY password;

GRANT CONNECT, RESOURCE TO testlum;
GRANT UNLIMITED TABLESPACE TO testlum;

ALTER SESSION SET CURRENT_SCHEMA = testlum;

CREATE SEQUENCE news_id_seq START WITH 1;

CREATE TABLE NEWS
(
    id         INTEGER   DEFAULT news_id_seq.nextval PRIMARY KEY,
    newsName   VARCHAR2(512)       NOT NULL UNIQUE,
    newsNumber INTEGER             NOT NULL UNIQUE,
    active     NUMBER(1) DEFAULT 0 NOT NULL,
    createdAt  TIMESTAMP           NOT NULL
);