disable_mlock = true
ui            = true

cluster_addr  = "https://vault-e2e:8201"
api_addr      = "https://vault-e2e:8200"

listener "tcp" {
  address     = "vault-e2e:8200"
  tls_disable = "true"
}

storage "file" {
  path = "/vault-data"
}